create table `13-1-2`
(
    direction  varchar(512) not null,
    hammerTime varchar(512) not null,
    hour       int          not null,
    minute     int          not null
);

create index direction
    on `13-1-2` (direction);

create index hammerTime
    on `13-1-2` (hammerTime);

create index hour
    on `13-1-2` (hour);

create index minute
    on `13-1-2` (minute);

INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Władysława IV', 10, 11);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Nowy Port Oliwska', 10, 12);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Przychodnia', 10, 13);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Rybołowców', 10, 14);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Kasztanowa', 10, 15);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Latarnia Morska', 10, 16);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Krasickiego', 10, 18);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Brzeźno Dom Zdrojowy', 10, 21);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Mazurska', 10, 22);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Wczasy', 10, 23);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Dworska', 10, 25);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'al. Płażyńskiego', 10, 26);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Grudziądzka', 10, 28);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Kolonia Uroda', 10, 29);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Kościuszki', 10, 31);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Mickiewicza', 10, 32);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Reja', 10, 33);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Wyspiańskiego', 10, 35);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Opera Bałtycka', 10, 38);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Traugutta', 10, 39);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Uniwersytet Medyczny', 10, 40);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Chodowieckiego', 10, 41);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Brama Oliwska', 10, 42);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Dworzec Główny', 10, 44);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Brama Wyżynna', 10, 47);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Okopowa', 10, 49);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Żabi Kruk', 10, 50);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Chmielna', 10, 51);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Akademia Muzyczna', 10, 53);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Brama Żuławska', 10, 55);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Głęboka', 10, 57);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Przeróbka', 10, 59);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Lenartowicza', 11, 0);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Sucharskiego', 11, 2);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Kaczeńce', 11, 3);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Ugory eMOCja', 11, 4);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Zimna', 11, 5);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Stogi', 11, 7);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Rozłogi', 11, 8);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Stogi Plaża', 11, 10);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Stogi Plaża', 11, 29);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Stogi', 11, 32);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Zimna', 11, 34);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Ugory eMOCja', 11, 35);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Kaczeńce', 11, 36);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Sucharskiego', 11, 38);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Lenartowicza', 11, 39);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Przeróbka', 11, 40);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Głęboka', 11, 42);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Brama Żuławska', 11, 44);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Akademia Muzyczna', 11, 46);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Chmielna', 11, 47);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Żabi Kruk', 11, 48);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Okopowa', 11, 50);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Brama Wyżynna', 11, 52);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Dworzec Główny', 11, 54);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Brama Oliwska', 11, 57);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Chodowieckiego', 11, 58);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Uniwersytet Medyczny', 11, 59);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Traugutta', 12, 1);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Opera Bałtycka', 12, 3);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Wyspiańskiego', 12, 6);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Reja', 12, 7);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Mickiewicza', 12, 9);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Kościuszki', 12, 11);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Kolonia Uroda', 12, 12);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Grudziądzka', 12, 13);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'al. Płażyńskiego', 12, 15);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Uczniowska', 12, 16);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Gdańska', 12, 18);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Sternicza', 12, 20);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Brzeźno Dom Zdrojowy', 12, 21);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Brzeźno Dom Zdrojowy', 12, 21);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Mazurska', 12, 22);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Wczasy', 12, 23);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Dworska', 12, 25);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'al. Płażyńskiego', 12, 26);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Grudziądzka', 12, 28);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Kolonia Uroda', 12, 29);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Kościuszki', 12, 31);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Mickiewicza', 12, 32);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Reja', 12, 33);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Wyspiańskiego', 12, 35);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Opera Bałtycka', 12, 38);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Traugutta', 12, 39);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Uniwersytet Medyczny', 12, 40);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Chodowieckiego', 12, 41);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Brama Oliwska', 12, 42);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Dworzec Główny', 12, 44);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Brama Wyżynna', 12, 47);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Okopowa', 12, 49);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Żabi Kruk', 12, 50);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Chmielna', 12, 51);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Akademia Muzyczna', 12, 53);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Brama Żuławska', 12, 55);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Głęboka', 12, 57);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Przeróbka', 12, 59);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Lenartowicza', 13, 0);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Sucharskiego', 13, 2);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Kaczeńce', 13, 3);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Ugory eMOCja', 13, 4);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Zimna', 13, 5);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Stogi', 13, 7);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Rozłogi', 13, 8);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Stogi Plaża', 13, 10);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Stogi Plaża', 13, 29);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Stogi', 13, 32);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Zimna', 13, 34);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Ugory eMOCja', 13, 35);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Kaczeńce', 13, 36);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Sucharskiego', 13, 38);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Lenartowicza', 13, 39);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Przeróbka', 13, 40);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Głęboka', 13, 42);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Brama Żuławska', 13, 44);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Akademia Muzyczna', 13, 46);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Chmielna', 13, 47);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Żabi Kruk', 13, 48);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Okopowa', 13, 50);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Brama Wyżynna', 13, 52);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Dworzec Główny', 13, 54);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Brama Oliwska', 13, 57);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Chodowieckiego', 13, 58);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Uniwersytet Medyczny', 13, 59);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Traugutta', 14, 1);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Opera Bałtycka', 14, 3);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Wyspiańskiego', 14, 6);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Reja', 14, 7);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Mickiewicza', 14, 9);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Kościuszki', 14, 11);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Kolonia Uroda', 14, 12);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Grudziądzka', 14, 13);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'al. Płażyńskiego', 14, 15);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Uczniowska', 14, 16);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Gdańska', 14, 18);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Sternicza', 14, 20);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Brzeźno Dom Zdrojowy', 14, 21);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Brzeźno Dom Zdrojowy', 14, 21);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Mazurska', 14, 22);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Wczasy', 14, 23);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Dworska', 14, 25);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'al. Płażyńskiego', 14, 26);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Grudziądzka', 14, 28);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Kolonia Uroda', 14, 29);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Kościuszki', 14, 31);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Mickiewicza', 14, 32);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Reja', 14, 33);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Wyspiańskiego', 14, 35);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Opera Bałtycka', 14, 38);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Traugutta', 14, 39);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Uniwersytet Medyczny', 14, 40);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Chodowieckiego', 14, 41);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Brama Oliwska', 14, 42);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Dworzec Główny', 14, 44);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Brama Wyżynna', 14, 47);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Okopowa', 14, 49);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Żabi Kruk', 14, 50);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Chmielna', 14, 51);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Akademia Muzyczna', 14, 53);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Brama Żuławska', 14, 55);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Głęboka', 14, 57);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Przeróbka', 14, 59);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Lenartowicza', 15, 0);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Sucharskiego', 15, 2);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Kaczeńce', 15, 3);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Ugory eMOCja', 15, 4);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Zimna', 15, 5);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi', 'Stogi', 15, 7);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Stogi', 15, 32);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Zimna', 15, 34);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Ugory eMOCja', 15, 35);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Kaczeńce', 15, 36);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Sucharskiego', 15, 38);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Lenartowicza', 15, 39);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Przeróbka', 15, 40);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Głęboka', 15, 42);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Brama Żuławska', 15, 44);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Akademia Muzyczna', 15, 46);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Chmielna', 15, 47);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Żabi Kruk', 15, 48);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Okopowa', 15, 50);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Brama Wyżynna', 15, 52);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Dworzec Główny', 15, 54);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Brama Oliwska', 15, 57);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Chodowieckiego', 15, 58);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Uniwersytet Medyczny', 15, 59);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Traugutta', 16, 1);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Opera Bałtycka', 16, 3);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Wyspiańskiego', 16, 6);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Reja', 16, 7);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Mickiewicza', 16, 9);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Kościuszki', 16, 11);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Kolonia Uroda', 16, 12);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Grudziądzka', 16, 13);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'al. Płażyńskiego', 16, 15);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Uczniowska', 16, 16);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Gdańska', 16, 18);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Sternicza', 16, 20);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Brzeźno Dom Zdrojowy', 'Brzeźno Dom Zdrojowy', 16, 21);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Brzeźno Dom Zdrojowy', 16, 21);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Mazurska', 16, 22);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Wczasy', 16, 23);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Dworska', 16, 25);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'al. Płażyńskiego', 16, 26);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Grudziądzka', 16, 28);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Kolonia Uroda', 16, 29);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Kościuszki', 16, 31);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Mickiewicza', 16, 32);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Reja', 16, 33);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Wyspiańskiego', 16, 35);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Opera Bałtycka', 16, 38);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Traugutta', 16, 39);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Uniwersytet Medyczny', 16, 40);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Chodowieckiego', 16, 41);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Brama Oliwska', 16, 42);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Dworzec Główny', 16, 44);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Brama Wyżynna', 16, 47);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Okopowa', 16, 49);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Żabi Kruk', 16, 50);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Chmielna', 16, 51);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Akademia Muzyczna', 16, 53);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Brama Żuławska', 16, 55);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Głęboka', 16, 57);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Przeróbka', 16, 59);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Lenartowicza', 17, 0);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Sucharskiego', 17, 2);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Kaczeńce', 17, 3);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Ugory eMOCja', 17, 4);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Zimna', 17, 5);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Stogi', 17, 7);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Rozłogi', 17, 8);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Stogi Plaża', 'Stogi Plaża', 17, 10);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Stogi Plaża', 17, 29);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Stogi', 17, 32);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Zimna', 17, 34);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Ugory eMOCja', 17, 35);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Kaczeńce', 17, 36);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Sucharskiego', 17, 38);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Lenartowicza', 17, 39);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Przeróbka', 17, 40);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Głęboka', 17, 42);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Brama Żuławska', 17, 44);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Akademia Muzyczna', 17, 46);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Chmielna', 17, 47);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Żabi Kruk', 17, 48);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Okopowa', 17, 50);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Brama Wyżynna', 17, 52);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Dworzec Główny', 17, 54);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Brama Oliwska', 17, 57);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Chodowieckiego', 17, 58);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Uniwersytet Medyczny', 17, 59);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Traugutta', 18, 1);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Opera Bałtycka', 18, 3);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Wyspiańskiego', 18, 6);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Reja', 18, 7);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Mickiewicza', 18, 9);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Kościuszki', 18, 11);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Kolonia Uroda', 18, 12);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Grudziądzka', 18, 13);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'al. Płażyńskiego', 18, 15);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Uczniowska', 18, 16);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Gdańska', 18, 18);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Sternicza', 18, 20);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Brzeźno Dom Zdrojowy', 18, 21);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Krasickiego', 18, 22);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Latarnia Morska', 18, 24);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Kasztanowa', 18, 25);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Na Zaspę', 18, 26);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Plac Wolności', 18, 28);
INSERT INTO ourDatabase.`13-1-2` (direction, hammerTime, hour, minute) VALUES ('Nowy Port Zajezdnia', 'Nowy Port Zajezdnia', 18, 29);
